/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.awt.event.KeyListener;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhtar
 */
public class v_kontrak extends javax.swing.JFrame {

    /**
     * Creates new form v_bahanBaku
     */
    public String getIdpetani;
    public String getIdlahan;

    public v_kontrak() {
        initComponents();
    }

    public int getcIdpetani() {
        return idpetani.getSelectedIndex();
    }

    public JComboBox<String> getIdpetani() {
        return idpetani;
    }

    public void check(ItemListener a) {
        this.idpetani.addItemListener(a);
    }

    public int getcIdlahan() {
        return idlahan.getSelectedIndex();
    }

    public JComboBox<String> getIdlahan() {
        return idlahan;
    }

    public void cek(ItemListener a) {
        this.idlahan.addItemListener(a);
    }

    public void getLuas(KeyListener a) {
        luas.addKeyListener(a);
    }

    public String getLuas() {
        return luas.getText();
    }

    public String getKontrak() {
        return idkontrak.getText();
    }

    public JTextField getPupuk() {
        return pupuk;
    }

    public JTextField getBibit() {
        return bibit;
    }

    public String getNama() {
        return mana.getText();
    }

    public String getLahan() {
        return namalahan.getText();
    }

    public String getLebar() {
        return luas.getText();
    }

    public String getTarget() {
        return target.getText();
    }

    public JTable getTabel() {
        return table;
    }

    public void setNama(String isi) {
        this.mana.setText(isi);
    }

    public void setLahan(String isi) {
        this.namalahan.setText(isi);
    }

    public void setLuas(String isi) {
        this.luas.setText(isi);
    }

    public void setIdkontak(String isi) {
        this.idkontrak.setText(isi);
    }

    public void setPupuk(String isi) {
        this.pupuk.setText(isi);
    }

    public void setBibit(String isi) {
        this.bibit.setText(isi);
    }

    public void setTarget(String isi) {
        this.target.setText(isi);
    }

    public void setIdpetani(String[] idpetani) {
        for (String a : idpetani) {
            this.idpetani.addItem(a);
        }
    }

    public void setIdpetani(int idpetani) {
        this.idpetani.setSelectedIndex(idpetani);
    }

    public void setIdlahan(String[] idlahan) {
        for (String a : idlahan) {
            this.idlahan.addItem(a);
        }
    }

    public void setIdlahan(int idlahan) {
        this.idlahan.setSelectedIndex(idlahan);
    }

    public int getSelectedRow() {
        return table.getSelectedRow();
    }

    public void setTable(DefaultTableModel table) {
        this.table.setModel(table);
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.table.getValueAt(baris, kolom);
    }

    public void addSaveListener(ActionListener e) {
        this.save.addActionListener(e);
    }

    public void addDeleteListener(ActionListener e) {
        this.delete.addActionListener(e);
    }

    public void addKeluarListener(ActionListener e) {
        this.keluar.addActionListener(e);
    }

    public void text(boolean status) {
        this.mana.setEnabled(status);
        this.namalahan.setEnabled(status);
        this.luas.setEnabled(status);
        this.pupuk.setEnabled(status);
        this.bibit.setEnabled(status);
    }

    public void button(boolean status) {
        this.save.setEnabled(status);
        this.delete.setEnabled(status);
    }

    public void buttonsave(boolean status) {
        this.save.setEnabled(status);
    }

    public void delete(boolean status) {
        this.delete.setEnabled(status);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idpetani = new javax.swing.JComboBox<>();
        idlahan = new javax.swing.JComboBox<>();
        mana = new javax.swing.JTextField();
        namalahan = new javax.swing.JTextField();
        luas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pupuk = new javax.swing.JTextField();
        bibit = new javax.swing.JTextField();
        idkontrak = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        target = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idpetani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        idpetani.setBorder(null);
        idpetani.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(idpetani, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 70, 20));

        idlahan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(idlahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 80, -1));

        mana.setBorder(null);
        mana.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mana.setEnabled(false);
        mana.setOpaque(false);
        getContentPane().add(mana, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 274, 220, 20));

        namalahan.setBorder(null);
        namalahan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        namalahan.setEnabled(false);
        namalahan.setOpaque(false);
        namalahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namalahanActionPerformed(evt);
            }
        });
        getContentPane().add(namalahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 220, 20));

        luas.setBorder(null);
        luas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        luas.setEnabled(false);
        luas.setOpaque(false);
        getContentPane().add(luas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 70, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setGridColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 580, 130));

        pupuk.setBorder(null);
        pupuk.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        pupuk.setEnabled(false);
        pupuk.setOpaque(false);
        getContentPane().add(pupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 70, 10));

        bibit.setBorder(null);
        bibit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        bibit.setEnabled(false);
        bibit.setOpaque(false);
        getContentPane().add(bibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 306, 60, 10));

        idkontrak.setBorder(null);
        idkontrak.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        idkontrak.setEnabled(false);
        idkontrak.setOpaque(false);
        getContentPane().add(idkontrak, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 70, -1));

        save.setBorder(null);
        save.setContentAreaFilled(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 60, 20));

        delete.setBorder(null);
        delete.setContentAreaFilled(false);
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 50, 20));

        keluar.setBorder(null);
        keluar.setContentAreaFilled(false);
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 50, 20));
        getContentPane().add(target, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 70, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("TARGET");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("KG");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/MENUKONTRAK_2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -5, -1, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namalahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namalahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namalahanActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_kontrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_kontrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_kontrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_kontrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_kontrak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bibit;
    private javax.swing.JButton delete;
    private javax.swing.JTextField idkontrak;
    private javax.swing.JComboBox<String> idlahan;
    private javax.swing.JComboBox<String> idpetani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField luas;
    private javax.swing.JTextField mana;
    private javax.swing.JTextField namalahan;
    private javax.swing.JTextField pupuk;
    private javax.swing.JButton save;
    private javax.swing.JTable table;
    private javax.swing.JTextField target;
    // End of variables declaration//GEN-END:variables
}
