/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhtar
 */
public class v_lahan extends javax.swing.JFrame {

    /**
     * Creates new form v_lahan
     */
    public v_lahan() {
        initComponents();
    }

    public String getIdlahan() {
        return idlahan.getText();
    }

    public String getNamalahan() {
        return namalahan.getText();
    }

    public String getLuas() {
        return luas.getText();
    }

    public String getAlamat() {
        return alamat.getText();
    }

    public void setIdlahan(String isi) {
        this.idlahan.setText(isi);
    }

    public void setNamalahan(String isi) {
        this.namalahan.setText(isi);
    }

    public void setLuas(String isi) {
        this.luas.setText(isi);
    }

    public void setAlamat(String isi) {
        this.alamat.setText(isi);
    }

    public int getSelectedRow() {
        return table.getSelectedRow();
    }

    public void setTable(DefaultTableModel table) {
        this.table.setModel(table);
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.table.getValueAt(baris, kolom);
    }

    public void addBtnSaveListener(ActionListener e) {
        this.save.addActionListener(e);
    }

    public void addBtnEditListener(ActionListener e) {
        this.edit.addActionListener(e);
    }

    public void addBtnUpdateListener(ActionListener e) {
        this.update.addActionListener(e);
    }

    public void addBtnDeleteListener(ActionListener e) {
        this.delete.addActionListener(e);
    }

    public void addBtnKeluarListener(ActionListener e) {
        this.btn_keluar.addActionListener(e);
    }

    public void text(boolean status) {
        this.namalahan.setEnabled(status);
        this.luas.setEnabled(status);
        this.alamat.setEnabled(status);

    }

    public void button(boolean status) {
        this.save.setEnabled(status);
        this.edit.setEnabled(status);
        this.delete.setEnabled(status);
    }

    public void save(boolean status) {
        this.save.setEnabled(status);
    }

    public void delete(boolean status) {
        this.delete.setEnabled(status);
    }

    public void edit(boolean status) {
        this.edit.setEnabled(status);
    }

    public void update(boolean status) {
        this.update.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        idlahan = new javax.swing.JTextField();
        namalahan = new javax.swing.JTextField();
        luas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        save.setBorder(null);
        save.setContentAreaFilled(false);
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 60, 20));

        edit.setBorder(null);
        edit.setContentAreaFilled(false);
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 50, 20));

        update.setText("Update");
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, -1, -1));

        delete.setBorder(null);
        delete.setContentAreaFilled(false);
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 533, 50, 20));

        btn_keluar.setBorder(null);
        btn_keluar.setContentAreaFilled(false);
        getContentPane().add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 50, 20));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, 120));

        idlahan.setBorder(null);
        idlahan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        idlahan.setEnabled(false);
        idlahan.setOpaque(false);
        idlahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idlahanActionPerformed(evt);
            }
        });
        getContentPane().add(idlahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 250, 20));

        namalahan.setBorder(null);
        namalahan.setOpaque(false);
        getContentPane().add(namalahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 266, 280, 20));

        luas.setBorder(null);
        luas.setOpaque(false);
        getContentPane().add(luas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 100, 20));

        alamat.setColumns(20);
        alamat.setRows(5);
        alamat.setBorder(null);
        alamat.setOpaque(false);
        jScrollPane2.setViewportView(alamat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 280, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/MENULAHAN.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 3, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idlahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idlahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idlahanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_lahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_lahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_lahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_lahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_lahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField idlahan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField luas;
    private javax.swing.JTextField namalahan;
    private javax.swing.JButton save;
    private javax.swing.JTable table;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
