/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhtar
 */
public class v_menuUtamaPengelolah extends javax.swing.JFrame {

    /**
     * Creates new form v_menuUtama
     */
    public v_menuUtamaPengelolah() {
        initComponents();
    }

    public void addBtnLahanListener(ActionListener e) {
        this.lahan.addActionListener(e);
    }

    public void addBtnKontrakListener(ActionListener e) {
        this.kontrak.addActionListener(e);
    }

    public void addBtnKeluarListener(ActionListener e) {
        this.btn_keluar.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_keluar = new javax.swing.JButton();
        lahan = new javax.swing.JButton();
        kontrak = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_keluar.setBorder(null);
        btn_keluar.setContentAreaFilled(false);
        getContentPane().add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 70, 50, 20));

        lahan.setBorder(null);
        lahan.setContentAreaFilled(false);
        getContentPane().add(lahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 265, 150, 50));

        kontrak.setBorder(null);
        kontrak.setContentAreaFilled(false);
        getContentPane().add(kontrak, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 265, 140, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/menuutama.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 810, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_menuUtamaPengelolah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_menuUtamaPengelolah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_menuUtamaPengelolah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_menuUtamaPengelolah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_menuUtamaPengelolah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_keluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kontrak;
    private javax.swing.JButton lahan;
    // End of variables declaration//GEN-END:variables
}
