/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhtar
 */
public class v_menuDivisiHasil extends javax.swing.JFrame {

    /**
     * Creates new form v_menuDivisiHasil
     */
    public v_menuDivisiHasil() {
        initComponents();
    }

    public String getHasil() {
        return hasil.getText();
    }

    public String getId() {
        return id.getText();
    }

    public String getLuas() {
        return luas.getText();
    }

    public String getNama() {
        return nama.getText();
    }

    public void setHasil(String isi) {
        this.hasil.setText(isi);
    }

    public void setId(String isi) {
        this.id.setText(isi);
    }

    public void setLuas(String isi) {
        this.luas.setText(isi);
    }

    public void setNama(String isi) {
        this.nama.setText(isi);
    }

    public int getcIdkontrak() {
        return idkontrak.getSelectedIndex();
    }

    public JComboBox<String> getIdkontrak() {
        return idkontrak;
    }

    public void check(ItemListener a) {
        this.idkontrak.addItemListener(a);
    }

    public void setIdkontrak(String[] idpetani) {
        for (String a : idpetani) {
            this.idkontrak.addItem(a);
        }
    }

    public void setIdkontrak(int idpetani) {
        this.idkontrak.setSelectedIndex(idpetani);
    }

    public int getSelectedRow() {
        return table.getSelectedRow();
    }

    public void setTable(DefaultTableModel table) {
        this.table.setModel(table);
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.table.getValueAt(baris, kolom);
    }

    public void addSaveListener(ActionListener e) {
        this.save.addActionListener(e);
    }

    public void addDeleteListener(ActionListener e) {
        this.delete.addActionListener(e);
    }

    public void addBtnKeluarListener(ActionListener e) {
        this.btn_keluar.addActionListener(e);
    }
//    public void addKeluarListener(ActionListener e) {
//        this.keluar.addActionListener(e);
//    }

    public void text(boolean status) {
        this.nama.setEnabled(status);
        this.luas.setEnabled(status);
        this.hasil.setEnabled(status);
    }

    public void button(boolean status) {
        this.save.setEnabled(status);
        this.delete.setEnabled(status);
    }

    public void buttonsave(boolean status) {
        this.save.setEnabled(status);
    }

    public void delete(boolean status) {
        this.delete.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_keluar = new javax.swing.JButton();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        idkontrak = new javax.swing.JComboBox<>();
        nama = new javax.swing.JTextField();
        luas = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_keluar.setBorder(null);
        btn_keluar.setContentAreaFilled(false);
        btn_keluar.setOpaque(false);
        getContentPane().add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 40, 20));

        save.setBorder(null);
        save.setContentAreaFilled(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 50, 20));

        delete.setBorder(null);
        delete.setContentAreaFilled(false);
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 50, 20));

        id.setText("jTextField1");
        id.setBorder(null);
        id.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        id.setEnabled(false);
        id.setOpaque(false);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        idkontrak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(idkontrak, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 80, -1));

        nama.setBorder(null);
        nama.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nama.setEnabled(false);
        nama.setOpaque(false);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 220, -1));

        luas.setBorder(null);
        luas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        luas.setEnabled(false);
        luas.setOpaque(false);
        getContentPane().add(luas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 80, -1));

        hasil.setBorder(null);
        hasil.setOpaque(false);
        getContentPane().add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 332, 70, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, 110));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hasil.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_menuDivisiHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_menuDivisiHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_menuDivisiHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_menuDivisiHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_menuDivisiHasil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton delete;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField id;
    private javax.swing.JComboBox<String> idkontrak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField luas;
    private javax.swing.JTextField nama;
    private javax.swing.JButton save;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
