/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Muhtar
 */
public class v_menuUtamaPetani extends javax.swing.JFrame {

    /**
     * Creates new form v_menuUtamaPetani
     */
    public v_menuUtamaPetani() {
        initComponents();
    }
    
//    public String getDomisilin() {
//        return domisilin.getText();
//    }
//    
//    public String getNama() {
//        return nama.getText();
//    }
//    
//    public String getTtl() {
//        return ttl.getText();
//    }
//    
//    public String getIdpetani() {
//        return idpetani.getText();
//    }
//    
//    public void setDomisilin(String isi) {
//        this.domisilin.setText(isi);
//    }
//    
//    public void setIdpetani(String isi) {
//        this.idpetani.setText(isi);
//    }
//    
//    public void setNama(String isi) {
//        this.nama.setText(isi);
//    }
//    
//    public void setTtl(String isi) {
//        this.ttl.setText(isi);
//    }
    
    public void addBtnLihatListener(ActionListener e) {
        this.btn_lihat.addActionListener(e);
    }

    public void addBtnKeluarListener(ActionListener e) {
        this.btn_keluar.addActionListener(e);
    }
    public void addPetaniListener(ActionListener e) {
        this.petani.addActionListener(e);
    }
    public void addHapusListener(ActionListener e) {
        this.hapus.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_keluar = new javax.swing.JButton();
        petani = new javax.swing.JButton();
        btn_lihat = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_keluar.setBorder(null);
        btn_keluar.setContentAreaFilled(false);
        getContentPane().add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 40, 20));

        petani.setBorder(null);
        petani.setContentAreaFilled(false);
        getContentPane().add(petani, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 150, 50));

        btn_lihat.setBorder(null);
        btn_lihat.setContentAreaFilled(false);
        getContentPane().add(btn_lihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 150, 50));

        hapus.setBorder(null);
        hapus.setContentAreaFilled(false);
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 150, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tampilanutama_2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 800, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_menuUtamaPetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_menuUtamaPetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_menuUtamaPetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_menuUtamaPetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_menuUtamaPetani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_lihat;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton petani;
    // End of variables declaration//GEN-END:variables
}
