/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhtar
 */
public class v_menuManagerProduksi extends javax.swing.JFrame {

    /**
     * Creates new form v_menuManagerProduksi
     */
    public v_menuManagerProduksi() {
        initComponents();
    }

    public String getId() {
        return id.getText();
    }

    public JTextField getHasil() {
        return hasil;
    }

    public JTextField getLuas() {
        return luas;
    }

    public JTextField getNamalahan() {
        return namalahan;
    }

    public JTextField getNamapetani() {
        return namapetani;
    }

    public JTextField getTarget() {
        return target;
    }
    
    
//
//    public String getLuas() {
//        return luas.getText();
//    }

//    public String getLahan() {
//        return namalahan.getText();
//    }
//    public JTextField getNama() {
//        return namapetani;
//    }
//
//    public String getTarget() {
//        return target.getText();
//    }
//
//    public String getHasil() {
//        return hasil.getText();
//    }
    public void setLuas(String isi) {
        this.luas.setText(isi);
    }

    public void setTarget(String isi) {
        this.target.setText(isi);
    }

    public void setHasil(String isi) {
        this.hasil.setText(isi);
    }

    public void setId(String isi) {
        this.id.setText(isi);
    }

    public void setLahan(String isi) {
        this.namalahan.setText(isi);
    }

    public void setNama(String isi) {
        this.namapetani.setText(isi);
    }

    public int getcIdkontrak() {
        return idkontrak.getSelectedIndex();
    }

    public JComboBox<String> getIdkontrak() {
        return idkontrak;
    }

    public void check(ItemListener a) {
        this.idkontrak.addItemListener(a);
    }

    public void setIdkontrak(String[] idkontrak) {
        for (String a : idkontrak) {
            this.idkontrak.addItem(a);
        }
    }

    public int getcIdhasil() {
        return idhasil.getSelectedIndex();
    }

    public JComboBox<String> getIdhasil() {
        return idhasil;
    }

    public void cek(ItemListener a) {
        this.idhasil.addItemListener(a);
    }

    public void setIdhasil(String[] idhasil) {
        for (String a : idhasil) {
            this.idhasil.addItem(a);
        }
    }

    public int getSelectedRow() {
        return table.getSelectedRow();
    }

    public void setTable(DefaultTableModel table) {
        this.table.setModel(table);
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.table.getValueAt(baris, kolom);
    }

    public void addSaveListener(ActionListener e) {
        this.save.addActionListener(e);
    }

    public void addDeleteListener(ActionListener e) {
        this.delete.addActionListener(e);
    }

    public void addBtnKeluarListener(ActionListener e) {
        this.logout.addActionListener(e);
    }
//    public void addKeluarListener(ActionListener e) {
//        this.keluar.addActionListener(e);
//    }

    public void text(boolean status) {
        this.namapetani.setEnabled(status);
        this.namalahan.setEnabled(status);
        this.luas.setEnabled(status);
        this.target.setEnabled(status);
        this.hasil.setEnabled(status);
    }

    public void button(boolean status) {
        this.save.setEnabled(status);
        this.delete.setEnabled(status);
    }

    public void buttonsave(boolean status) {
        this.save.setEnabled(status);
    }

    public void delete(boolean status) {
        this.delete.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        idkontrak = new javax.swing.JComboBox<>();
        namapetani = new javax.swing.JTextField();
        namalahan = new javax.swing.JTextField();
        luas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        target = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        idhasil = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        save.setBorder(null);
        save.setContentAreaFilled(false);
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 340, 50, 20));

        delete.setBorder(null);
        delete.setContentAreaFilled(false);
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 343, 50, 20));

        logout.setBorder(null);
        logout.setContentAreaFilled(false);
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 50, 30));

        id.setBorder(null);
        id.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        id.setEnabled(false);
        id.setOpaque(false);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 70, -1));

        idkontrak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(idkontrak, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 80, -1));

        namapetani.setBorder(null);
        namapetani.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        namapetani.setEnabled(false);
        namapetani.setOpaque(false);
        getContentPane().add(namapetani, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 296, 220, 10));

        namalahan.setBorder(null);
        namalahan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        namalahan.setEnabled(false);
        namalahan.setOpaque(false);
        getContentPane().add(namalahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 70, 20));

        luas.setBorder(null);
        luas.setOpaque(false);
        getContentPane().add(luas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 70, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, 120));

        target.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetActionPerformed(evt);
            }
        });
        getContentPane().add(target, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 80, -1));
        getContentPane().add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 130, -1));

        idhasil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(idhasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/target.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, -2, -1, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void targetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_menuManagerProduksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_menuManagerProduksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_menuManagerProduksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_menuManagerProduksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_menuManagerProduksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField id;
    private javax.swing.JComboBox<String> idhasil;
    private javax.swing.JComboBox<String> idkontrak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField luas;
    private javax.swing.JTextField namalahan;
    private javax.swing.JTextField namapetani;
    private javax.swing.JButton save;
    private javax.swing.JTable table;
    private javax.swing.JTextField target;
    // End of variables declaration//GEN-END:variables
}
